# coding: utf-8
from sqlalchemy import Column, Date, Integer, MetaData, String, Table, text

metadata = MetaData()

t_tb_pedidos_eliminados = Table(
    'tb_pedidos_eliminados', metadata,
    Column('CODIGO_PK', Integer, nullable=False),
    Column('TB_PEDIDOS_NIT', String(100, 'utf8mb4_unicode_ci')),
    Column('TB_PEDIDOS_CLIENTE', String(100, 'utf8mb4_unicode_ci')),
    Column('TB_PEDIDOS_MARCA', String(100, 'utf8mb4_unicode_ci')),
    Column('TB_PEDIDOS_CODIGO_ZONA', String(100, 'utf8mb4_unicode_ci')),
    Column('TB_PEDIDOS_NOMBRE_ZONA', String(100, 'utf8mb4_unicode_ci')),
    Column('TB_PEDIDOS_CIUDAD', String(100, 'utf8mb4_unicode_ci')),
    Column('TB_PEDIDOS_CAMPANA', String(100, 'utf8mb4_unicode_ci')),
    Column('TB_PEDIDOS_FECHA', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('TB_PEDIDOS_NRO_FACTURA', String(100, 'utf8mb4_unicode_ci')),
    Column('TB_PEDIDOS_NRO_PEDIDO', String(100, 'utf8mb4_unicode_ci')),
    Column('TB_PEDIDOS_CONSECUTIVO', String(100, 'utf8mb4_unicode_ci')),
    Column('TB_PEDIDOS_BARCODE_CAJA', String(100, 'utf8mb4_unicode_ci')),
    Column('TB_PEDIDOS_TIPO_PRODUCTO', String(100, 'utf8mb4_unicode_ci')),
    Column('TB_PEDIDOS_CONTENIDO_CAJA', String(100, 'utf8mb4_unicode_ci')),
    Column('TB_PEDIDOS_ID_ASESORA', String(145, 'utf8mb4_unicode_ci'), nullable=False),
    Column('TB_PEDIDOS_CEDULA', String(100, 'utf8mb4_unicode_ci')),
    Column('TB_PEDIDOS_NOMBRE_ASESORA', String(100, 'utf8mb4_unicode_ci')),
    Column('TB_PEDIDOS_DIRECCION_ASESORA', String(200, 'utf8mb4_unicode_ci')),
    Column('TB_PEDIDOS_DPTO_ASESORA', String(100, 'utf8mb4_unicode_ci')),
    Column('TB_PEDIDOS_BARRIO_ASESORA', String(100, 'utf8mb4_unicode_ci')),
    Column('TB_PEDIDOS_VEREDA', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('TB_PEDIDOS_MUNICIPIO_ENVIEXPRESS', String(100, 'utf8mb4_unicode_ci'), nullable=False),
    Column('TB_PEDIDOS_CELULAR_ASESORA', String(100, 'utf8mb4_unicode_ci')),
    Column('TB_PEDIDOS_MOVIL_ASESORA', String(100, 'utf8mb4_unicode_ci')),
    Column('TB_PEDIDOS_AUDITAR', String(100, 'utf8mb4_unicode_ci')),
    Column('TB_PEDIDOS_CAJAS', String(45, 'utf8mb4_unicode_ci')),
    Column('TIEMPO_TRANSITO_BODEGA', String(33, 'utf8mb4_unicode_ci'), nullable=False),
    Column('TIEMPO_BODEGA_REPARTO', String(33, 'utf8mb4_unicode_ci'), nullable=False),
    Column('TIEMPO_BODEGA_DIGITALIZADO', String(33, 'utf8mb4_unicode_ci'), nullable=False),
    Column('TIEMPO_TRANSITO_DIGITALIZADO', String(33, 'utf8mb4_unicode_ci'), nullable=False),
    Column('TIEMPO_REPARTO_DIGITALIZADO', String(33, 'utf8mb4_unicode_ci'), nullable=False),
    Column('TIPO_DE_CARGA', String(100, 'utf8mb4_unicode_ci'), nullable=False),
    Column('TIPO_DESTINO', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('PROMESA_HRS', Integer, nullable=False),
    Column('ANS', String(10, 'utf8mb4_unicode_ci'), nullable=False),
    Column('METODO_DE_PAGO', String(45, 'utf8mb4_unicode_ci'), nullable=False, server_default=text("'KM'")),
    Column('ESTADO', String(45, 'utf8mb4_unicode_ci'), nullable=False, server_default=text("'REGISTRADO'")),
    Column('EN_BODEGA_FECHA', String(100, 'utf8mb4_unicode_ci'), nullable=False),
    Column('EN_REPARTO_FECHA', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('ESTADO_ENTREGADO', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('EN_ENTREGADO_FECHA', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('DIGITALIZADO_FECHA', String(64, 'utf8mb4_unicode_ci'), nullable=False),
    Column('SINIESTRO_FECHA', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('ESTADO_DIGITALIZADO', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('ESTADO_NO_ENTREGADO', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('EN_NO_ENTREGADO_FECHA', String(100, 'utf8mb4_unicode_ci'), nullable=False),
    Column('ESTADO_REENVIO', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('EN_REENVIO_FECHA', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('EN_RETORNO_FECHA', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('REZAGO_FECHA', String(64, 'utf8mb4_unicode_ci'), nullable=False),
    Column('NOVEDAD', String(500, 'utf8mb4_unicode_ci'), nullable=False),
    Column('NOTA', String(500, 'utf8mb4_unicode_ci'), nullable=False),
    Column('NOTAS_DE_OPERACION', String(345, 'utf8mb4_unicode_ci'), nullable=False),
    Column('CEDI', String(100, 'utf8mb4_unicode_ci'), nullable=False),
    Column('ACTIVO', String(45, 'utf8mb4_unicode_ci'), server_default=text("'1'")),
    Column('FECHA_HORA', String(100, 'utf8mb4_unicode_ci'), nullable=False),
    Column('FECHA', Date, nullable=False, server_default=text("'2024-01-01'")),
    Column('CODIGO_DE_CARGA', String(100, 'utf8mb4_unicode_ci'), nullable=False),
    Column('ORDEN_DE_SERVICIO', String(100, 'utf8mb4_unicode_ci'), nullable=False),
    Column('ORDEN_DE_DESPACHO', String(100, 'utf8mb4_unicode_ci'), nullable=False),
    Column('PLACA', String(50, 'utf8mb4_unicode_ci'), nullable=False),
    Column('PLACA_DE_REPARTO', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('TRANSPORTADOR', String(200, 'utf8mb4_unicode_ci'), nullable=False),
    Column('FECHA_CARGA', String(100, 'utf8mb4_unicode_ci'), nullable=False),
    Column('ENCONTRADO_EN_CONTEO', String(45, 'utf8mb4_unicode_ci'), nullable=False, server_default=text("'No'")),
    Column('CONSECUTIVO_CONTEO', String(100, 'utf8mb4_unicode_ci'), nullable=False),
    Column('CODIGO_DE_CARGUE', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('MANIFIESTO_URBANO', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('CODIGO_DE_REENVIO', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('CODIGO_DE_RETORNO', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('ESTADO_SEGMENTACION_DE_CONTEO', String(45, 'utf8mb4_unicode_ci'), nullable=False, server_default=text("'REGISTRADO'")),
    Column('ESTADO_CODIGO_DE_ZONA', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('CODIGO_CIUDAD', String(100, 'utf8mb4_unicode_ci'), nullable=False),
    Column('MAIL_GROUP', String(100, 'utf8mb4_unicode_ci'), nullable=False),
    Column('PLACA_MP', String(100, 'utf8mb4_unicode_ci'), nullable=False),
    Column('NOMBRE_CONDUCTOR', String(100, 'utf8mb4_unicode_ci'), nullable=False),
    Column('LINK', String(364, 'utf8mb4_unicode_ci'), nullable=False),
    Column('FOTOGRAFIA', String(245, 'utf8mb4_unicode_ci'), nullable=False),
    Column('TEST', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('VR_UNITARIO_MANIFIESTO', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('USUARIO_REGISTRO', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('USUARIO_EN_BODEGA', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('USUARIO_EN_REPARTO', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('TOKEN', String(64, 'utf8mb4_unicode_ci'), nullable=False),
    Column('DESPACHO_API', String(64, 'utf8mb4_unicode_ci'), nullable=False),
    Column('DESPACHO_ID', String(64, 'utf8mb4_unicode_ci'), nullable=False),
    Column('CODE_STATUS', String(64, 'utf8mb4_unicode_ci'), nullable=False),
    Column('EN_TRANSBORDO_FECHA', String(64, 'utf8mb4_unicode_ci'), nullable=False),
    Column('CHECK_TRANSITO', String(45, 'utf8mb4_unicode_ci'), nullable=False, server_default=text("'report'")),
    Column('CHECK_TRANSITO_A_CEDI', String(45, 'utf8mb4_unicode_ci'), nullable=False, server_default=text("'report'")),
    Column('CHECK_EN_BODEGA_VERIFICACION', String(45, 'utf8mb4_unicode_ci'), nullable=False, server_default=text("'report'")),
    Column('CHECK_EN_BODEGA', String(45, 'utf8mb4_unicode_ci'), nullable=False, server_default=text("'report'")),
    Column('CHECK_EN_REPARTO', String(45, 'utf8mb4_unicode_ci'), nullable=False, server_default=text("'report'")),
    Column('CHECK_DIGITALIZADO', String(45, 'utf8mb4_unicode_ci'), nullable=False, server_default=text("'report'")),
    Column('RADICADO', Integer, nullable=False),
    Column('RADICADOSC', Integer, nullable=False),
    Column('ESTADO_MOVE', Integer, nullable=False),
    Column('ESTADO_MOVE_RECORDS', Integer, nullable=False),
    Column('ESTADO_MOVE_EC', Integer, nullable=False, server_default=text("'0'")),
    Column('CODIGO_FLETE', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('VR_UNITARIO_DIST', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('VR_UNITARIO_VEREDA_DIST', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('VR_ADICIONAL_DIST', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('VR_FLETE_DIST', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('OTROS_COSTOS_DIST', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('PRE_LIQUIDACION', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('FECHA_PRE_LIQUIDACION', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('ESTADO_PRE_LIQUIDACION', Integer, nullable=False, server_default=text("'0'")),
    Column('REGISTRO_MOVIDO_PRE_LIQUIDACION', Integer, nullable=False, server_default=text("'0'")),
    Column('ORDEN_DE_COMPRA', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('FECHA_ORDEN_DE_COMPRA', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('VR_FAC', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('VR_FTE_FAC', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('NO_FAC', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('FECHA_FAC', String(45, 'utf8mb4_unicode_ci'), nullable=False),
    Column('ESTADO_TRACKING', Integer, nullable=False),
    Column('ESTADO_PRELIQUIDACION', Integer, nullable=False),
    Column('NTF_EN_REPARTO', Integer, nullable=False),
    Column('NTF_DIGITALIZADO', Integer, nullable=False),
    Column('RUTA', String(45, 'utf8mb4_unicode_ci'), nullable=False, server_default=text("'SIN DEFINIR'")),
    Column('FECHA_PROMESA', Date)
)


    