name: MySQL Setup

on: [push]

jobs:
  setup-mysql:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.39
        env:
          MYSQL_ROOT_PASSWORD: Akira
          MYSQL_DATABASE: enviexpress
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run MySQL script
      run: mysql -h 127.0.0.1 -u root -proot enviexpress < sql/scripts.sql
